### ISSUE TITLE
Unity 5.5.0f3打开工程有报错

### ISSUE THREAD

**Issue by mic89** [woshihuo12/UnityHello#2]
其中

1. UnityEngine.LightShadowResolution =>UnityEngine.Rendering.LightShadowResolution
2. 有一个int转string的参数传递错误
3. Renderer.motionVectors 此变量没有

So工程跑不起来...

**Comment by woshihuo12** [comment]
兄弟，说明里有 5.4.4.  换个环境玩儿吧。。。
